public with sharing class abc {

    public abc(Custom controller) {
    name = 'vName';
    amount = 1234;
     system.debug('----in constructor abc');
    }

public string name{get;set;}
public integer amount{get;set;}
//public string closeDate{get;set;}
//public abc(ApexPages.StandardController acon) { }
 /*public Void doSomething()
 {
name ='vibhor';
amount=300;
 system.debug('----in custom abc');
 }*/
}